openapi: 3.0.0
info:
  description: Nekoverse Echo API
  version: 1.0.0
  title: Neko Echo Api
  license:
    name: MIT
    url: "https://github.com/nekoverse-api/neko-echo-api/blob/main/LICENSE"
tags:
  - name: echo
    description: CRUD

paths:
  /{path}:
    get:
      tags:
        - echos
      summary: Get echo response
      operationId: getBy
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashMapObject"
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
        "default":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
    post:
      tags:
        - echos
      summary: Post echo response
      operationId: postBy
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashMapObject"
      responses:
        "200":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
        "default":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
    put:
      tags:
        - echos
      summary: Put echo response
      operationId: putBy
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashMapObject"
      responses:
        "200":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
        "default":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"

    patch:
      tags:
        - echos
      summary: Patch echo response
      operationId: patchBy
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashMapObject"
      responses:
        "200":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
        "default":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"

    delete:
      tags:
        - echos
      summary: Delete echo response
      operationId: deleteBy
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashMapObject"
      responses:
        "200":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
        "default":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"

    options:
      tags:
        - echos
      summary: Options echo response
      operationId: optionsBy
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashMapObject"
      responses:
        "200":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"
        "default":
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EchoResponse"

components:
  parameters:
    path:
      name: path
      in: query
      schema:
        type: string
        minLength: 1

  schemas:
    HashMapObject:
      type: object
      additionalProperties: true

    EchoResponse:
      title: Echo Response
      description: Echo response used to test api tools
      type: object
      properties:
        version:
          type: string
        sid:
          type: string
        url:
          type: string
        path:
          type: string
        method:
          type: string
        args:
          type: object
          additionalProperties: true
        data:
          type: object
          additionalProperties: true
        headers:
          type: object
          additionalProperties: true
        createdAt:
          type: string
      required:
        - sid
        - url
