# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Docker Build & Publish Native Image to DockerHub
on:
  release:
    types: [created]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jannemattila/get-version-from-tag@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Native Docker Image
      run: ./gradlew dockerBuildNative
      env:
        NEKO_ECHO_API_VERSION: ${{ steps.get_version.outputs.version }}

    - name: Publish Native Docker Image to DockerHub
      run: ./gradlew dockerPushNative
      env:
        NEKO_ECHO_API_VERSION: ${{ steps.get_version.outputs.version }}
